### ISSUE TITLE
Support shipping address

### ISSUE THREAD

**Issue by wilsonminer** [christophercliff/flatmarket-schema#4]
The billingAddress configuration is supported in the stripe schema, but including the shippingAddress option results in a build error: ""shippingAddress" is not allowed".

https://stripe.com/docs/checkout#integration-options-shipping-address

**Comment by christophercliff** [comment]
I was under the impression Stripe had dropped support for `shippingAddress`, but the documentation was vague about it. It's possible they brought it back. If so, would be a useful feature.

If anybody wants to investigate, please do.

**Comment by wilsonminer** [comment]
It was undocumented for a while, but it's back in the official documentation as of some changes they made to the Checkout in August.

**Comment by christophercliff** [comment]
I see. Found some more info here: http://engineering.koalasafe.com/how-to-capture-shipping-address-with-stripe-checkout/.

Definitely a nice feature to add, but pretty substantial project.

**Comment by wilsonminer** [comment]
Understood! I'll keep an eye out.

**Comment by christophercliff** [comment]
@wilsonminer Shipping address support landed in the latest version. Please report back if you end up using in production, would be great if we could link to your work as an example.

**Comment by wilsonminer** [comment]
Thanks for the update! I'll let you know if we end up using it.
